### ISSUE TITLE
Bug in decoy creation

### ISSUE THREAD

**Issue by ypriverol** [nf-core/pgdb#1]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/pgdb pipeline documentation](https://nf-co.re/nf-core/pgdb/usage)

## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag: 

## Additional context

```
Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/bin/pypgatk_cli.py", line 48, in <module>
      main()
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/bin/pypgatk_cli.py", line 44, in main
      cli()
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/core.py", line 829, in __call__
      return self.main(*args, **kwargs)
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/core.py", line 782, in main
      rv = self.invoke(ctx)
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
      return f(get_current_context(), *args, **kwargs)
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/pypgatk/commands/proteindb_decoy.py", line 80, in generate_database
      proteindb_decoy.decoy_database()
    File "/opt/conda/envs/nf-core-pgdb-1.0dev/lib/python3.9/site-packages/pypgatk/proteomics/db/decoy_pyrat.py", line 233, in decoy_database
      fasta.close()
  AttributeError: 'FastaIterator' object has no attribute 'close'

Work dir:
  /Users/yperez/IdeaProjects/github-repo/BDP/nf-core-pgdb/work/19/d6ff3d5c551ee89fc0711ccf562903

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'main.nf' at line: 759 or see '.nextflow.log' file for more details
```

**Comment by ypriverol** [comment]
decoy tests has passed https://github.com/nf-core/pgdb/runs/1853421511?check_suite_focus=true
